theme: jekyll-theme-slate
title: Naruto once said, Once you question your own beliefs, then it's all over.
description: Investigating cross between Religion, Mathematical formulas, and Cyber Security.
